<?php

use Drupal\Core\Menu\MenuLinkInterface;
use Drupal\menu_link_content\Plugin\Menu\MenuLinkContent;

/**
* Implements hook_preprocess_menu().
*/
function custom_translation_menu_preprocess_menu(&$variables) {
  if ($variables['menu_name'] == 'main' || $variables['menu_name'] == "footer-first"  || $variables['menu_name'] == "footer-second" || $variables['menu_name'] == "footer-third") {
   $language = Drupal::languageManager()->getCurrentLanguage()->getId();
    foreach ($variables['items'] as $key => &$item) {
      $menuLinkEntity = custom_translation_menu_load_link_entity_by_link($item['original_link']);

      if ($menuLinkEntity != NULL) {
        $languages = $menuLinkEntity->getTranslationLanguages();
        // Remove links which is not translated to current language.
        if (!array_key_exists($language, $languages)) {
          unset($variables['items'][$key]);
        }
      }
    }
  }
}

function custom_translation_menu_load_link_entity_by_link(MenuLinkInterface $menuLinkContentPlugin) {
  $entity = NULL;

  if ($menuLinkContentPlugin instanceof MenuLinkContent) {
    list($entity_type, $uuid) = explode(':', $menuLinkContentPlugin->getPluginId(), 2);
    $entity = \Drupal::entityManager()->loadEntityByUuid($entity_type, $uuid);
  }
  return $entity;
}